# -*- coding: utf-8 -*-
"""v890 — 撮影した写真から伝票部分だけを切り出して読み取り・保存する。
   Motoさん依頼。自動で枠を出すが、勝手には切らない（確認してから適用）。
   透過置換・CRLF保持・アンカーは1件だけ。"""

P = 'index.html'
d = open(P, 'rb').read()
orig_crlf = d.count(b'\r\n')


def rep(old_s, new_s, note):
    global d
    old, new = old_s.encode('utf-8'), new_s.encode('utf-8')
    n = d.count(old)
    assert n == 1, 'anchor count=%d (expected 1): %s' % (n, note)
    d = d.replace(old, new, 1)
    print('OK  ', note)


BLOCK = (
"/* ===== v890: 伝票の範囲だけを切り出す =====\r\n"
"   Motoさん依頼：撮った写真からレシート／Invoice の部分だけを読み取って保存したい。\r\n"
"   決めごと:\r\n"
"   ・自動で枠を出すが、勝手には切らない。必ず確認画面を挟む。\r\n"
"     黙って切ると合計行が枠外に落ちても誰も気づけない。7月のレシート消失と\r\n"
"     同じ「失敗が見えない」型の事故になるため、ここは1タップ増やす価値がある。\r\n"
"   ・検出できないときは全体を枠にする。今より悪くなる状態を作らない。\r\n"
"   ・OpenCV は使わない（CDN で数MB、オフラインで動かない）。自前で組む。\r\n"
"   ・切った画像で OCR も保存もする。読み取り精度も上がる。\r\n"
"   ・PDF で入稿されたものは切らない。すでに書類として整っているうえ、\r\n"
"     v889 で元PDFをそのまま保存する方針にしたため。 */\r\n"
"\r\n"
"/* 大津の二値化しきい値 */\r\n"
"function _dcOtsu(hist, total){\r\n"
"  var sum=0, i;\r\n"
"  for(i=0;i<256;i++) sum+=i*hist[i];\r\n"
"  var sumB=0, wB=0, best=0, thr=127;\r\n"
"  for(i=0;i<256;i++){\r\n"
"    wB+=hist[i]; if(!wB) continue;\r\n"
"    var wF=total-wB; if(!wF) break;\r\n"
"    sumB+=i*hist[i];\r\n"
"    var mB=sumB/wB, mF=(sum-sumB)/wF;\r\n"
"    var v=wB*wF*(mB-mF)*(mB-mF);\r\n"
"    if(v>best){ best=v; thr=i; }\r\n"
"  }\r\n"
"  return thr;\r\n"
"}\r\n"
"/* 最大連結成分の外接矩形。4近傍・スタック式（再帰は深さで落ちる） */\r\n"
"function _dcLargestBox(mask, W, H){\r\n"
"  var seen=new Uint8Array(W*H), stack=new Int32Array(W*H);\r\n"
"  var best=null, bestN=0;\r\n"
"  for(var p=0;p<W*H;p++){\r\n"
"    if(!mask[p]||seen[p]) continue;\r\n"
"    var sp=0; stack[sp++]=p; seen[p]=1;\r\n"
"    var n=0, x0=W, y0=H, x1=-1, y1=-1;\r\n"
"    while(sp){\r\n"
"      var q=stack[--sp], qx=q%W, qy=(q-qx)/W;\r\n"
"      n++;\r\n"
"      if(qx<x0)x0=qx; if(qx>x1)x1=qx;\r\n"
"      if(qy<y0)y0=qy; if(qy>y1)y1=qy;\r\n"
"      if(qx>0     && mask[q-1] && !seen[q-1]){ seen[q-1]=1; stack[sp++]=q-1; }\r\n"
"      if(qx<W-1   && mask[q+1] && !seen[q+1]){ seen[q+1]=1; stack[sp++]=q+1; }\r\n"
"      if(qy>0     && mask[q-W] && !seen[q-W]){ seen[q-W]=1; stack[sp++]=q-W; }\r\n"
"      if(qy<H-1   && mask[q+W] && !seen[q+W]){ seen[q+W]=1; stack[sp++]=q+W; }\r\n"
"    }\r\n"
"    if(n>bestN){ bestN=n; best=[x0,y0,x1,y1]; }\r\n"
"  }\r\n"
"  return best ? {box:best, n:bestN} : null;\r\n"
"}\r\n"
"/* rgba: 縮小済み画像の画素（getImageData().data）/ W,H: そのサイズ\r\n"
"   返り値は 0〜1 の相対座標。判定できなければ null（＝全体を枠にする） */\r\n"
"function detectDocRect(rgba, W, H){\r\n"
"  var N=W*H, gray=new Uint8Array(N), hist=new Uint32Array(256);\r\n"
"  for(var i=0,p=0;i<N;i++,p+=4){\r\n"
"    var g=(rgba[p]*299+rgba[p+1]*587+rgba[p+2]*114)/1000|0;\r\n"
"    gray[i]=g; hist[g]++;\r\n"
"  }\r\n"
"  var thr=_dcOtsu(hist,N);\r\n"
"  /* 紙が明るいか暗いかを決める。伝票は中央・背景は縁、という前提で比べる。\r\n"
"     黒いテーブルにも白いトレーにも効かせるため、決め打ちにしない。 */\r\n"
"  var bSum=0,bN=0,cSum=0,cN=0;\r\n"
"  var mx0=(W*0.3)|0, mx1=(W*0.7)|0, my0=(H*0.3)|0, my1=(H*0.7)|0;\r\n"
"  for(var y=0;y<H;y++){\r\n"
"    for(var x=0;x<W;x++){\r\n"
"      var v=gray[y*W+x];\r\n"
"      if(x<W*0.06||x>W*0.94||y<H*0.06||y>H*0.94){ bSum+=v; bN++; }\r\n"
"      else if(x>=mx0&&x<=mx1&&y>=my0&&y<=my1){ cSum+=v; cN++; }\r\n"
"    }\r\n"
"  }\r\n"
"  var borderMean=bN?bSum/bN:128, centerMean=cN?cSum/cN:128;\r\n"
"  var docIsBright=centerMean>=borderMean;\r\n"
"  /* 白い紙を白い机に置いた等、差が無いときは切らない。\r\n"
"     無理に切ると合計行を落としかねないので、判定できないことを返す。 */\r\n"
"  if(Math.abs(centerMean-borderMean)<12) return null;\r\n"
"  var mask=new Uint8Array(N);\r\n"
"  for(var k=0;k<N;k++) mask[k]= docIsBright ? (gray[k]>thr?1:0) : (gray[k]<thr?1:0);\r\n"
"  var r=_dcLargestBox(mask,W,H);\r\n"
"  if(!r) return null;\r\n"
"  var x0=r.box[0], y0=r.box[1], x1=r.box[2], y1=r.box[3];\r\n"
"  var bw=x1-x0+1, bh=y1-y0+1, frac=(bw*bh)/N;\r\n"
"  /* 明らかにおかしい結果は捨てる。切りすぎ・細すぎ・ほぼ全面。 */\r\n"
"  if(frac<0.08) return null;                      /* 小さすぎ＝紙ではなく反射など */\r\n"
"  if(frac>0.97) return null;                      /* ほぼ全面＝切る意味がない */\r\n"
"  if(bw<W*0.12||bh<H*0.12) return null;           /* 細すぎ */\r\n"
"  if(r.n/(bw*bh)<0.55) return null;               /* 埋まりが薄い＝紙ではない */\r\n"
"  /* 縁を少し足す。ぴったりだと端の文字が欠けて見える。 */\r\n"
"  var m=Math.max(2, Math.round(Math.max(W,H)*0.015));\r\n"
"  x0=Math.max(0,x0-m); y0=Math.max(0,y0-m);\r\n"
"  x1=Math.min(W-1,x1+m); y1=Math.min(H-1,y1+m);\r\n"
"  return { x:x0/W, y:y0/H, w:(x1-x0+1)/W, h:(y1-y0+1)/H };\r\n"
"}\r\n"
"\r\n"
"/* ---- 範囲の確認画面 ---- */\r\n"
"var _cropS=null, _CROP_H=13;\r\n"
"function _cropDraw(){\r\n"
"  var S=_cropS; if(!S||!S.canvas) return;\r\n"
"  var c=S.canvas, ctx=c.getContext('2d'), b=S.box;\r\n"
"  ctx.clearRect(0,0,c.width,c.height);\r\n"
"  ctx.drawImage(S.base,0,0);\r\n"
"  ctx.fillStyle='rgba(20,16,12,.58)';\r\n"
"  ctx.fillRect(0,0,c.width,b.y);\r\n"
"  ctx.fillRect(0,b.y+b.h,c.width,c.height-(b.y+b.h));\r\n"
"  ctx.fillRect(0,b.y,b.x,b.h);\r\n"
"  ctx.fillRect(b.x+b.w,b.y,c.width-(b.x+b.w),b.h);\r\n"
"  ctx.strokeStyle='#f0661f'; ctx.lineWidth=3; ctx.strokeRect(b.x,b.y,b.w,b.h);\r\n"
"  ctx.strokeStyle='rgba(255,255,255,.32)'; ctx.lineWidth=1;\r\n"
"  for(var i=1;i<3;i++){\r\n"
"    ctx.beginPath(); ctx.moveTo(b.x+b.w*i/3,b.y); ctx.lineTo(b.x+b.w*i/3,b.y+b.h); ctx.stroke();\r\n"
"    ctx.beginPath(); ctx.moveTo(b.x,b.y+b.h*i/3); ctx.lineTo(b.x+b.w,b.y+b.h*i/3); ctx.stroke();\r\n"
"  }\r\n"
"  [[b.x,b.y],[b.x+b.w,b.y],[b.x,b.y+b.h],[b.x+b.w,b.y+b.h]].forEach(function(p){\r\n"
"    ctx.fillStyle='#f0661f'; ctx.beginPath(); ctx.arc(p[0],p[1],_CROP_H,0,6.2832); ctx.fill();\r\n"
"    ctx.fillStyle='#fff';    ctx.beginPath(); ctx.arc(p[0],p[1],_CROP_H*0.42,0,6.2832); ctx.fill();\r\n"
"  });\r\n"
"}\r\n"
"function _cropInfo(){\r\n"
"  var S=_cropS, el=document.getElementById('crop-info'); if(!S||!el) return;\r\n"
"  var pw=Math.round(S.box.w/S.scale), ph=Math.round(S.box.h/S.scale);\r\n"
"  var pct=Math.round((S.box.w*S.box.h)/(S.canvas.width*S.canvas.height)*100);\r\n"
"  el.textContent=pw+'×'+ph+' px（写真の '+pct+'%）';\r\n"
"}\r\n"
"function _cropPos(e){\r\n"
"  var c=_cropS.canvas, r=c.getBoundingClientRect();\r\n"
"  return { x:(e.clientX-r.left)*(c.width/r.width), y:(e.clientY-r.top)*(c.height/r.height) };\r\n"
"}\r\n"
"function cropDown(e){\r\n"
"  var S=_cropS; if(!S) return; e.preventDefault();\r\n"
"  var p=_cropPos(e), b=S.box, R=_CROP_H*1.9;\r\n"
"  var cs=[[b.x,b.y],[b.x+b.w,b.y],[b.x,b.y+b.h],[b.x+b.w,b.y+b.h]];\r\n"
"  S.drag=null;\r\n"
"  for(var i=0;i<4;i++){\r\n"
"    var dx=p.x-cs[i][0], dy=p.y-cs[i][1];\r\n"
"    if(Math.sqrt(dx*dx+dy*dy)<R){ S.drag={type:'c', i:i}; break; }\r\n"
"  }\r\n"
"  if(!S.drag && p.x>=b.x && p.x<=b.x+b.w && p.y>=b.y && p.y<=b.y+b.h){\r\n"
"    S.drag={type:'m', ox:p.x-b.x, oy:p.y-b.y};\r\n"
"  }\r\n"
"  if(S.drag){ try{ S.canvas.setPointerCapture(e.pointerId); }catch(_){} }\r\n"
"}\r\n"
"function cropMove(e){\r\n"
"  var S=_cropS; if(!S||!S.drag) return; e.preventDefault();\r\n"
"  var p=_cropPos(e), b=S.box, W=S.canvas.width, H=S.canvas.height, MIN=44;\r\n"
"  if(S.drag.type==='m'){\r\n"
"    b.x=Math.max(0, Math.min(W-b.w, p.x-S.drag.ox));\r\n"
"    b.y=Math.max(0, Math.min(H-b.h, p.y-S.drag.oy));\r\n"
"  } else {\r\n"
"    var x0=b.x, y0=b.y, x1=b.x+b.w, y1=b.y+b.h;\r\n"
"    var px=Math.max(0,Math.min(W,p.x)), py=Math.max(0,Math.min(H,p.y));\r\n"
"    if(S.drag.i===0){ x0=Math.min(px,x1-MIN); y0=Math.min(py,y1-MIN); }\r\n"
"    if(S.drag.i===1){ x1=Math.max(px,x0+MIN); y0=Math.min(py,y1-MIN); }\r\n"
"    if(S.drag.i===2){ x0=Math.min(px,x1-MIN); y1=Math.max(py,y0+MIN); }\r\n"
"    if(S.drag.i===3){ x1=Math.max(px,x0+MIN); y1=Math.max(py,y0+MIN); }\r\n"
"    b.x=x0; b.y=y0; b.w=x1-x0; b.h=y1-y0;\r\n"
"  }\r\n"
"  _cropDraw(); _cropInfo();\r\n"
"}\r\n"
"function cropUp(){ if(_cropS) _cropS.drag=null; }\r\n"
"function cropReset(){\r\n"
"  var S=_cropS; if(!S) return;\r\n"
"  var c=S.canvas;\r\n"
"  S.box = S.auto\r\n"
"    ? { x:S.auto.x*c.width, y:S.auto.y*c.height, w:S.auto.w*c.width, h:S.auto.h*c.height }\r\n"
"    : { x:0, y:0, w:c.width, h:c.height };\r\n"
"  _cropDraw(); _cropInfo();\r\n"
"}\r\n"
"function cropApply(useAll){\r\n"
"  var S=_cropS; if(!S) return;\r\n"
"  _cropS=null;\r\n"
"  var done=function(f){\r\n"
"    try{ URL.revokeObjectURL(S.url); }catch(e){}\r\n"
"    closeModalDirect();\r\n"
"    S.resolve(f);\r\n"
"  };\r\n"
"  if(useAll) return done(S.file);\r\n"
"  try{\r\n"
"    var sx=Math.max(0, Math.round(S.box.x/S.scale));\r\n"
"    var sy=Math.max(0, Math.round(S.box.y/S.scale));\r\n"
"    var sw=Math.min(S.iw-sx, Math.round(S.box.w/S.scale));\r\n"
"    var sh=Math.min(S.ih-sy, Math.round(S.box.h/S.scale));\r\n"
"    if(sw<8||sh<8) return done(S.file);\r\n"
"    var cv=document.createElement('canvas'); cv.width=sw; cv.height=sh;\r\n"
"    var cx=cv.getContext('2d');\r\n"
"    cx.fillStyle='#fff'; cx.fillRect(0,0,sw,sh);\r\n"
"    cx.drawImage(S.img, sx,sy,sw,sh, 0,0,sw,sh);\r\n"
"    cv.toBlob(function(b){\r\n"
"      if(!b){ showToast('切り出しに失敗したので全体を使います','warning'); return done(S.file); }\r\n"
"      var nm=String(S.file.name||'receipt').replace(/\\.[^.]+$/,'')+'_crop.jpg';\r\n"
"      /* 縮小は入れない。長辺2400への調整は _invNormalizeJpeg が一手に引き受ける。 */\r\n"
"      done(new File([b], nm, {type:'image/jpeg'}));\r\n"
"    }, 'image/jpeg', 0.95);\r\n"
"  }catch(e){\r\n"
"    console.warn('crop apply', e);\r\n"
"    showToast('切り出しに失敗したので全体を使います','warning');\r\n"
"    done(S.file);\r\n"
"  }\r\n"
"}\r\n"
"/* 写真を受け取り、確認後のファイルを返す。何かあれば元のファイルをそのまま返す。 */\r\n"
"function askInvoiceCrop(file){\r\n"
"  return new Promise(function(resolve){\r\n"
"    var url;\r\n"
"    try{ url=URL.createObjectURL(file); }catch(e){ return resolve(file); }\r\n"
"    var img=new Image();\r\n"
"    img.onerror=function(){ try{URL.revokeObjectURL(url);}catch(e){} resolve(file); };\r\n"
"    img.onload=function(){\r\n"
"      try{\r\n"
"        var iw=img.naturalWidth||img.width, ih=img.naturalHeight||img.height;\r\n"
"        if(!iw||!ih) throw new Error('size unknown');\r\n"
"        /* 検出は長辺360pxで。iPhoneでも一瞬で終わる大きさ。 */\r\n"
"        var ds=Math.min(1, 360/Math.max(iw,ih));\r\n"
"        var dw=Math.max(20,Math.round(iw*ds)), dh=Math.max(20,Math.round(ih*ds));\r\n"
"        var dcv=document.createElement('canvas'); dcv.width=dw; dcv.height=dh;\r\n"
"        var dcx=dcv.getContext('2d',{willReadFrequently:true});\r\n"
"        dcx.drawImage(img,0,0,dw,dh);\r\n"
"        var auto=null;\r\n"
"        try{ auto=detectDocRect(dcx.getImageData(0,0,dw,dh).data, dw, dh); }\r\n"
"        catch(e){ console.warn('detectDocRect', e); }\r\n"
"        /* プレビューは一度だけ描いて使い回す。指で動かすたびに元画像を\r\n"
"           縮小し直すと、大きい写真でカクつくため。 */\r\n"
"        var CW=Math.min(760, iw), scale=CW/iw, ch=Math.max(1,Math.round(ih*scale));\r\n"
"        var base=document.createElement('canvas'); base.width=CW; base.height=ch;\r\n"
"        base.getContext('2d').drawImage(img,0,0,CW,ch);\r\n"
"        openModal('<div class=\"modal-title\"><i class=\"ti ti-crop\" style=\"color:var(--accent)\"></i> '\r\n"
"          + t('伝票の範囲を確認','Check the receipt area')+'</div>'\r\n"
"          + '<div style=\"font-size:11.5px;color:var(--muted);margin-bottom:7px;line-height:1.6\">'\r\n"
"          + (auto\r\n"
"              ? '<i class=\"ti ti-sparkles\" style=\"color:var(--green)\"></i> '\r\n"
"                + t('伝票らしい範囲を自動で囲みました。','Detected the receipt area.')\r\n"
"              : '<i class=\"ti ti-alert-triangle\" style=\"color:var(--yellow)\"></i> '\r\n"
"                + t('自動で見つけられませんでした。指で囲ってください。','Could not detect it — drag to set the area.'))\r\n"
"          + '<br>' + t('読み取りも保存も、この枠の中だけになります。','Both OCR and the saved file use only this area.')\r\n"
"          + '</div>'\r\n"
"          + '<canvas id=\"crop-cv\" width=\"'+CW+'\" height=\"'+ch+'\" '\r\n"
"          + 'style=\"width:100%;height:auto;border-radius:10px;display:block;touch-action:none;'\r\n"
"          + 'background:var(--surface2);max-height:56vh;object-fit:contain\" '\r\n"
"          + 'onpointerdown=\"cropDown(event)\" onpointermove=\"cropMove(event)\" '\r\n"
"          + 'onpointerup=\"cropUp()\" onpointercancel=\"cropUp()\" onpointerleave=\"cropUp()\"></canvas>'\r\n"
"          + '<div style=\"display:flex;align-items:center;gap:8px;margin-top:7px\">'\r\n"
"          + '<span id=\"crop-info\" style=\"font-size:11px;color:var(--muted)\"></span>'\r\n"
"          + '<button class=\"btn btn-secondary btn-sm\" style=\"margin-left:auto\" onclick=\"cropReset()\">'\r\n"
"          + '<i class=\"ti ti-refresh\"></i> '+t('枠を戻す','Reset')+'</button></div>'\r\n"
"          + '<div class=\"btn-row\">'\r\n"
"          + '<button class=\"btn btn-secondary\" onclick=\"cropApply(true)\">'\r\n"
"          + '<i class=\"ti ti-photo\"></i> '+t('全体を使う','Use whole photo')+'</button>'\r\n"
"          + '<button class=\"btn btn-primary\" onclick=\"cropApply(false)\">'\r\n"
"          + '<i class=\"ti ti-scan\"></i> '+t('この範囲で読み取る','Use this area')+'</button></div>');\r\n"
"        var canvas=document.getElementById('crop-cv');\r\n"
"        if(!canvas){ try{URL.revokeObjectURL(url);}catch(e){} return resolve(file); }\r\n"
"        _cropS={ canvas:canvas, base:base, img:img, url:url, file:file,\r\n"
"                 iw:iw, ih:ih, scale:scale, auto:auto, drag:null,\r\n"
"                 box: auto ? { x:auto.x*CW, y:auto.y*ch, w:auto.w*CW, h:auto.h*ch }\r\n"
"                           : { x:CW*0.05, y:ch*0.05, w:CW*0.90, h:ch*0.90 },\r\n"
"                 resolve:resolve };\r\n"
"        _cropDraw(); _cropInfo();\r\n"
"      }catch(e){\r\n"
"        console.warn('askInvoiceCrop', e);\r\n"
"        try{ URL.revokeObjectURL(url); }catch(_){}\r\n"
"        resolve(file);\r\n"
"      }\r\n"
"    };\r\n"
"    img.src=url;\r\n"
"  });\r\n"
"}\r\n"
)

rep("async function realInvoiceOCR(input){\r\n",
    BLOCK + "async function realInvoiceOCR(input){\r\n",
    "検出ロジックと範囲確認画面を追加")

# 撮影・選択の入口（画像のみ。PDFは切らない）
rep("  } else {\r\n    await runInvoiceOCR(file);\r\n  }\r\n  try{ input.value=''; }catch(e){}\r\n}\r\n",
    "  } else {\r\n"
    "    /* v890: 伝票の範囲を確認してから読み取る。使うのは枠の中だけ。 */\r\n"
    "    var use = await askInvoiceCrop(file);\r\n"
    "    await runInvoiceOCR(use || file);\r\n"
    "  }\r\n"
    "  try{ input.value=''; }catch(e){}\r\n}\r\n",
    "onInvoiceFilePicked に範囲確認を挟む")

rep("async function realInvoiceOCR(input){\r\n"
    "  var file=input&&input.files&&input.files[0];\r\n"
    "  if(!file) return;\r\n"
    "  await runInvoiceOCR(file);\r\n",
    "async function realInvoiceOCR(input){\r\n"
    "  var file=input&&input.files&&input.files[0];\r\n"
    "  if(!file) return;\r\n"
    "  /* v890: こちらの入口も同じ扱いにする。片方だけ切れる状態を作らない。 */\r\n"
    "  var use = _invIsPdf(file) ? file : await askInvoiceCrop(file);\r\n"
    "  await runInvoiceOCR(use || file);\r\n",
    "realInvoiceOCR にも範囲確認を挟む")

rep("const APP_VERSION = '889';", "const APP_VERSION = '890';", "APP_VERSION 889 -> 890")

open(P, 'wb').write(d)

d2 = open(P, 'rb').read()
crlf = d2.count(b'\r\n'); lf = d2.count(b'\n')
print('\nCRLF %d (was %d) / lone LF %d' % (crlf, orig_crlf, lf - crlf))
assert lf - crlf == 0, 'lone LF detected'

s = open('sw.js', 'rb').read()
assert s.count(b"const SW_BUILD = '889';") == 1
open('sw.js', 'wb').write(s.replace(b"const SW_BUILD = '889';", b"const SW_BUILD = '890';", 1))
print('OK   SW_BUILD 889 -> 890')
