import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {PGlite} from './runtime/node_modules/@electric-sql/pglite/dist/index.js';
import {parseCaseReply,replyChoices,responseReceipt} from '../bot/case-replies.mjs';
import {dailyDisposition,formatMorningSummary,createHandler} from '../supabase/functions/ops-bot/handler.mjs';
const gm='00000000-0000-4000-8000-000000000001',crew='00000000-0000-4000-8000-000000000002',g='C'+'a'.repeat(32),u='U'+'a'.repeat(32),hq='U'+'b'.repeat(32);
let db;const q=async(s,p=[])=>(await db.query(s,p)).rows;const get=async id=>(await q('select * from bot_cases where id=$1',[id]))[0];
const write=async(op,c,data={},actor=gm)=>(await q('select bot_case_write($1,$2,$3,$4,$5) v',[op,actor,c?.id||null,c?.version||null,JSON.stringify(data)]))[0].v;
const find=async(key,kind='labor',fp='a',store='TEST')=>write('finding',null,{source_key:key,kind,store_id:store,business_date:'2026-08-01',subject:'Synthetic',payload:{fingerprint:fp,amount:50,scope:'payment'}});
const reply=async(c,action='fixed',note='Synthetic correction',actor=gm,line=null,due=null)=>(await q('select bot_case_respond($1,$2,$3,$4,$5,$6,$7,$8) v',[c.id,c.version,action,note,actor,line?g:null,line,due]))[0].v;
async function init(){db=new PGlite();await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create table auth.users(id uuid primary key);create table store_config(store_id text primary key,name text,active boolean default true);create table manager_auth(user_id uuid primary key,role text);insert into store_config values('TEST','Test',true),('OTHER','Other',true);insert into manager_auth values('${gm}','gm'),('${crew}','office_crew');grant select on store_config,manager_auth to service_role;`);
for(const f of ['ops-bot','ops-bot-all-stores','ops-bot-monitor','ops-bot-mentions','ops-bot-daily-range','ops-bot-auth','ops-bot-morning-summary','ops-bot-morning-summary-details'])await db.exec(fs.readFileSync(new URL('../db/'+f+'.sql',import.meta.url),'utf8'));
await find('pre-existing');await db.exec(fs.readFileSync(new URL('../supabase/migrations/20260910184520_bot_case_closure.sql',import.meta.url),'utf8'));
await q('insert into bot_groups(group_id,enabled,all_stores) values($1,true,true)',[g]);
for(const [user,role] of [[u,'manager'],[hq,'hq']])await q('insert into bot_settings(key,value) values($1,$2)',['line_responder:'+g+':'+user,JSON.stringify({enabled:true,role,stores:['TEST'],approved_by:gm,display_name:'Synthetic '+role})]);
await q("insert into bot_settings(key,value) values('morning_summary',$1)",[JSON.stringify({enabled:true,group_id:g,label:'HQ'})]);}
test('strict bilingual replies, buttons, and status routing',()=>{
assert.deepEqual(parseCaseReply('＃１２３ 修正済み 退勤時刻を修正'),{code:'#123',action:'fixed',note:'退勤時刻を修正'});
for(const text of ['#12 確認済み・変更なし 正当な取消','#12 confirmed no change approved cancellation'])assert.equal(parseCaseReply(text).action,'unchanged');
for(const text of ['#12 未完了','#12 修正済み','#12 修正済み ですか？','#12 fixed?','#12 done','#12 その他 確認中','#12 fixed no?'])assert.equal(parseCaseReply(text).invalid,true,text);
assert.equal(parseCaseReply('了解です'),null);assert.equal(parseCaseReply('#1 対応中 2026-09-20 確認予定').due_date,'2026-09-20');
assert.equal(replyChoices('#123').items.length,4);assert.equal(dailyDisposition({status:'hq_review'},'2026-09-10'),'hq_review');assert.equal(dailyDisposition({status:'verify'},'2026-09-10'),'verify');
assert.match(responseReceipt({code:'#1',status:'correction',payload:{returned:{note:'Need detail'},response:{note:'Old'}}}),/Need detail/);
});
test('closure database workflows',async t=>{await init();
await t.test('old cases get short codes and retained aliases; duplicate findings do not consume numbers',async()=>{const a=(await q("select * from bot_cases where source_key='pre-existing'"))[0];assert.equal(a.code,'#1');assert.match(a.legacy_code,/^B-/);const b=await find('second');await find('second');const c=await find('third');assert.equal(Number(c.code.slice(1)),Number(b.code.slice(1))+1);});
await t.test('store manager correction waits for proof; proof closes attendance',async()=>{let c=await find('fixed');c=await reply(c,'fixed','Corrected clock',null,u);assert.equal(c.status,'verify');c=await write('verified',c,{clean:true,checked_at:new Date().toISOString()},null);assert.equal(c.status,'done');assert.ok(c.closed_at);assert.equal(c.payload.closure.type,'verified');});
await t.test('finance proof alone needs HQ, including no response cases',async()=>{for(const kind of ['void','unpaid']){let c=await find('finance-'+kind,kind);c=await write('verified',c,{clean:true,verification_type:kind==='void'?'payment_void_recovered':'unpaid_paid'},null);assert.equal(c.status,'hq_review');c=await reply(c,'hq_approve','Verified funds');assert.equal(c.status,'done');}});
await t.test('unchanged requires HQ and monitor cannot bypass it',async()=>{let c=await find('unchanged');c=await reply(c,'unchanged','Valid long shift',null,u);assert.equal(c.status,'hq_review');c=await write('verified',c,{clean:true},null);assert.equal(c.status,'hq_review');await assert.rejects(()=>reply(c,'hq_approve','My own approval',null,u),/forbidden/);c=await reply(c,'hq_approve','HQ verified',null,hq);assert.equal(c.status,'done');});
await t.test('other close and return preserve reasons, due date, and approval history',async()=>{let c=await find('other');c=await reply(c,'other','Duplicate case',null,u);c=await reply(c,'hq_return','Specify other case');assert.equal(c.status,'correction');assert.ok(c.due_date);assert.equal(c.payload.returned.note,'Specify other case');c=await reply(c,'other','Duplicate of #1',null,u);c=await reply(c,'hq_approve','Checked #1');assert.equal(c.payload.response.note,'Duplicate of #1');assert.equal(c.payload.closure.note,'Checked #1');});
await t.test('returned finance evidence cannot bypass a requested store explanation',async()=>{let c=await find('returned-finance','unpaid');c=await reply(c,'fixed','Settled');c=await reply(c,'hq_return','Need explanation');const v=c.status_version;c=await write('verified',c,{clean:true,verification_type:'unpaid_paid'},null);assert.equal(c.status,'correction');assert.equal(c.status_version,v);c=await reply(c,'fixed','Explained and settled');assert.equal(c.status,'hq_review');assert.ok(c.status_version>v);});
await t.test('due HQ returns are eligible for a daily reminder without treating evidence as clean',async()=>{let c=await find('return-reminder','unpaid');c=await reply(c,'fixed','Settled');c=await reply(c,'hq_return','Need more explanation');const today=new Date(Date.now()-10*3600000).toISOString().slice(0,10);await q('update bot_cases set due_date=$1 where id=$2',[today,c.id]);c=await get(c.id);c.due_date=today;assert.equal(dailyDisposition(c,today),'action');const message={type:'text',text:'Please explain'};const result=(await q('select bot_reserve_daily_send($1,$2,$3,$4,$5,$6,$7,$8) v',[gm,c.id,c.version,crypto.randomUUID(),g,message.text,JSON.stringify(message),today]))[0].v;assert.equal(result.reminder_date,today);await q('select bot_finish_send($1,$2)',[result.id,'sent']);c=await get(c.id);assert.equal(c.status,'correction');c=await write('verified',c,{clean:true,verification_type:'unpaid_paid'},null);assert.equal(c.status,'correction');});
await t.test('continued work requires a valid future due date; blank notes rejected',async()=>{let c=await find('continuing');await assert.rejects(()=>reply(c,'continue','Working'),/due_date_required/);await assert.rejects(()=>reply(c,'fixed','  '),/note_required/);const due=new Date(Date.now()+86400000).toISOString().slice(0,10);c=await reply(c,'continue','Working',null,u,due);assert.equal(c.due_date,due);assert.equal(c.status,'correction');});
await t.test('future deadlines block new individual and daily reminders even with fresh findings',async()=>{let c=await find('future-deadline');const today=new Date(Date.now()-10*3600000).toISOString().slice(0,10),due=new Date(Date.now()+86400000).toISOString().slice(0,10);c=await reply(c,'continue','Checking',gm,null,due);await q("update bot_cases set last_checked_at=now(),last_check='{\"message\":\"still_flagged_or_manual_review\"}' where id=$1",[c.id]);c=await get(c.id);const message={type:'text',text:'Reminder'};assert.equal(dailyDisposition({...c,due_date:due},today),'scheduled');await assert.rejects(()=>q('select bot_reserve_send($1,$2,$3,$4,$5,$6)',[gm,c.id,c.version,crypto.randomUUID(),g,message.text]),/due_date_not_reached/);await assert.rejects(()=>q('select bot_reserve_daily_send($1,$2,$3,$4,$5,$6,$7,$8)',[gm,c.id,c.version,crypto.randomUUID(),g,message.text,JSON.stringify(message),today]),/due_date_not_reached/);});
await t.test('changed evidence clears old return and verification before delivery and monitoring',async()=>{let c=await find('changed-return','unpaid');c=await reply(c,'fixed','Settled');c=await write('verified',c,{clean:true,verification_type:'unpaid_paid'},null);c=await reply(c,'hq_return','Explain');c=await find('changed-return','unpaid','new');assert.equal(c.status,'review');assert.equal(c.payload.returned,undefined);assert.equal(c.payload.verification,undefined);const o=(await q('select bot_reserve_send($1,$2,$3,$4,$5,$6) v',[gm,c.id,c.version,crypto.randomUUID(),g,'New finding']))[0].v;await q('select bot_finish_send($1,$2)',[o.id,'sent']);c=await get(c.id);assert.equal(c.status,'waiting');c=await write('verified',c,{clean:true,verification_type:'unpaid_paid'},null);assert.equal(c.status,'hq_review');});
await t.test('unregistered users, crews and other-store managers cannot change status',async()=>{let c=await find('restricted');for(const actor of [crew])await assert.rejects(()=>reply(c,'fixed','Fake',actor),/forbidden/);await assert.rejects(()=>reply(c,'fixed','Fake',null,'U'+'c'.repeat(32)),/forbidden/);const other=await find('other-store','labor','a','OTHER');await assert.rejects(()=>reply(other,'fixed','Fake',null,u),/forbidden/);});
await t.test('webhook deduplicates, notes do not close, and legacy codes resolve',async()=>{let c=(await q("select * from bot_cases where source_key='pre-existing'"))[0];const ingest=(event,code,action=null)=>q('select bot_reply_ingest($1,$2,$3,$4,$5,$6,$7) v',[event,g,u,code+' response',code,action,'Synthetic note']);await ingest('note',c.code);assert.equal((await get(c.id)).status,'review');await ingest('legacy',c.legacy_code,'fixed');const once=await get(c.id);await ingest('legacy',c.legacy_code,'fixed');assert.equal((await get(c.id)).version,once.version);assert.equal(once.status,'verify');});
await t.test('stale HQ approvals do not close changed evidence; reviewed unchanged data stays closed',async()=>{let c=await find('reopen');c=await reply(c,'unchanged','Valid');const old=c;c=await find('reopen','labor','b');assert.equal(c.status,'review');assert.equal(c.payload.response,undefined);await assert.rejects(()=>reply(old,'hq_approve','Old evidence'),/conflict/);c=await reply(c,'unchanged','New evidence valid');c=await reply(c,'hq_approve','Approved');c=await find('reopen','labor','b');assert.equal(c.status,'done');c=await find('reopen','labor','c');assert.equal(c.status,'review');assert.equal(c.closed_at,null);});
await t.test('legacy APIs cannot bypass approval; no reminders while HQ/verification pending',async()=>{let c=await find('legacy-api');await assert.rejects(()=>write('acknowledge',c,{note:'Bypass'}),/hq_review_required/);await assert.rejects(()=>write('reported',c),/response_required/);c=await reply(c,'unchanged','Valid');await assert.rejects(()=>write('correction',c),/invalid_state/);await assert.rejects(()=>q('select bot_reserve_send($1,$2,$3,$4,$5,$6)',[gm,c.id,c.version,crypto.randomUUID(),g,'Reminder']),/closed_case/);});
await t.test('direct no-change closure retains the detected fingerprint despite older fixed evidence',async()=>{let c=await find('direct-nochange');c=await reply(c,'fixed','Corrected');await q("update bot_cases set payload=payload||'{\"verification\":{\"clean\":true}}'::jsonb where id=$1",[c.id]);await q("update bot_settings set value=value||'{\"unchanged_hq\":false}'::jsonb where key='closure_rules'");c=await get(c.id);c=await reply(c,'unchanged','Actually valid');assert.equal(c.status,'done');c=await find('direct-nochange');assert.equal(c.status,'done');});
await t.test('rule flags combine rather than bypass finance; revocation is immediate',async()=>{await q("update bot_settings set value=value||'{\"unchanged_hq\":false}'::jsonb where key='closure_rules'");let c=await find('rules','void');c=await reply(c,'unchanged','Checked',null,u);assert.equal(c.status,'hq_review');await q("update bot_settings set value=value||'{\"enabled\":false}'::jsonb where key=$1",['line_responder:'+g+':'+u]);const n=await find('revoked');await assert.rejects(()=>reply(n,'fixed','Revoked',null,u),/forbidden/);});
await t.test('morning snapshot includes carryover and HQ statuses; lifecycle queue is service only',async()=>{const snap=(await q('select bot_morning_snapshot() v'))[0].v;assert.ok(snap.details.some(c=>c.status==='hq_review'));assert.ok(snap.details.some(c=>c.business_date==='2026-08-01'));assert.ok(snap.recent_closed.length);const fmt=formatMorningSummary(snap);assert.match(fmt.text,/本部確認待ち/);assert.ok(fmt.messages.every(m=>m.text.length<=4900));assert.ok((await q("select count(*)::int n from bot_events where kind='lifecycle_notice'"))[0].n>0);for(const role of ['anon','authenticated']){await db.exec('set role '+role);await assert.rejects(()=>q('select bot_needs_hq($1,$2,$3)',['labor','fixed',0]),/permission denied/);await assert.rejects(()=>q('select * from bot_cases'),/permission denied/);await db.exec('reset role');}});
await t.test('signed LINE webhook changes the real test database and responds; redelivery has no second effect',async()=>{
 const c=await find('signed-webhook');let replies=0;
 const h=createHandler({env:k=>({SUPABASE_URL:'https://db.test',SUPABASE_SERVICE_ROLE_KEY:'service',LINE_CHANNEL_SECRET:'synthetic',LINE_CHANNEL_ACCESS_TOKEN:'token'})[k],fetch:async(url,init)=>{
  if(url.endsWith('/rpc/bot_reply_ingest')){const p=JSON.parse(init.body);return Response.json((await q('select bot_reply_ingest($1,$2,$3,$4,$5,$6,$7,$8) v',[p.p_event,p.p_group,p.p_user,p.p_text,p.p_code,p.p_action,p.p_note,p.p_due]))[0].v);}
  if(url.endsWith('/message/reply')){replies++;assert.match(JSON.parse(init.body).messages[0].text,/本部確認待ち/);return Response.json({});}throw Error('unexpected path '+url);
 }});
 const bytes=new TextEncoder().encode(JSON.stringify({events:[{type:'message',webhookEventId:'signed-event',replyToken:'synthetic-reply',source:{groupId:g,userId:hq},message:{type:'text',text:c.code+' その他・終了 Duplicate entry'}}]}));
 const key=await crypto.subtle.importKey('raw',new TextEncoder().encode('synthetic'),{name:'HMAC',hash:'SHA-256'},false,['sign']);const sig=btoa(String.fromCharCode(...new Uint8Array(await crypto.subtle.sign('HMAC',key,bytes))));
 const request=signature=>new Request('https://fn.test?route=line',{method:'POST',headers:{'x-line-signature':signature},body:bytes});
 assert.equal((await h(request('bad'))).status,401);assert.equal((await get(c.id)).status,'review');
 assert.equal((await h(request(sig))).status,200);assert.equal((await get(c.id)).status,'hq_review');assert.equal(replies,1);
 const version=(await get(c.id)).version;assert.equal((await h(request(sig))).status,200);assert.equal((await get(c.id)).version,version);assert.equal(replies,1);
});
await db.close();});
